<?php

if ( !defined('IN_PHPBB') )
{
	die("Hacking attempt");
}

$sql[] = 'ALTER TABLE ' . $table_prefix . 'auth_access ADD COLUMN `auth_globalannounce` TINYINT(1)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'auth_access ADD COLUMN `auth_voteban` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'auth_access ADD COLUMN `auth_ban` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'auth_access ADD COLUMN `auth_greencard` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'auth_access ADD COLUMN `auth_bluecard` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'auth_access ADD COLUMN `auth_suggest_event` tinyint(2) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'auth_access ADD COLUMN `auth_download` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'auth_access MODIFY COLUMN `forum_id` smallint(5) DEFAULT "0" NOT NULL';

$sql[] = 'ALTER TABLE ' . $table_prefix . 'banlist ADD COLUMN `user_name` VARCHAR(50) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'banlist ADD COLUMN `reason` VARCHAR(75) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'banlist ADD COLUMN `baned_by` VARCHAR(50) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'banlist ADD COLUMN `ban_time` INT(11) DEFAULT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'banlist ADD COLUMN `ban_expire_time` INT(11) DEFAULT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'banlist ADD COLUMN `ban_by_userid` MEDIUMINT(8) DEFAULT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'banlist ADD COLUMN `ban_priv_reason` TEXT';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'banlist ADD COLUMN `ban_pub_reason_mode` TINYINT(1) DEFAULT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'banlist ADD COLUMN `ban_pub_reason` TEXT';

$sql[] = 'ALTER TABLE ' . $table_prefix . 'categories ADD COLUMN `cat_icon` VARCHAR(255) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'categories ADD COLUMN `cat_sponsor_img` VARCHAR(255) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'categories ADD COLUMN `cat_sponsor_alt` VARCHAR(255) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'categories ADD COLUMN `cat_sponsor_url` VARCHAR(255) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'categories ADD COLUMN `parent_forum_id` SMALLINT(5) UNSIGNED DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'categories ADD COLUMN `cat_hier_level` TINYINT UNSIGNED DEFAULT "0" NOT NULL';
			
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_hier_level` TINYINT UNSIGNED DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_issub` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_views` MEDIUMINT(8) UNSIGNED DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `image_ever_thumb` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `auth_globalannounce` TINYINT(2) DEFAULT "3" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_icon` VARCHAR(255) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `icon_enable` TINYINT(1) NOT NULL DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `answered_enable` TINYINT(1) NOT NULL DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `move_next` INT(11) DEFAULT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `move_enable` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `auth_voteban` TINYINT(2) DEFAULT "1" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_enter_limit` MEDIUMINT(8) UNSIGNED DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `auth_ban` TINYINT(2) NOT NULL DEFAULT "3"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `auth_greencard` TINYINT(2) NOT NULL DEFAULT "5"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `auth_bluecard` TINYINT(2) NOT NULL DEFAULT "1"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `auth_suggest_event` tinyint(2) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `is_default` tinyint(2) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `points_disabled` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `events_forum` TINYINT(1) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `auth_download` TINYINT(2) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_external` TINYINT(1) NOT NULL DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_redirect_url` TEXT';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_redirects_user` MEDIUMINT(8) UNSIGNED DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_redirects_guest` MEDIUMINT(8) UNSIGNED DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_ext_newwin` TINYINT(1) NOT NULL DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_ext_image` TEXT';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums MODIFY COLUMN `forum_id` SMALLINT(5) NOT NULL auto_increment';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums MODIFY COLUMN `cat_id` MEDIUMINT(8) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_rules` TEXT NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `amazon_display` TINYINT(1)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_thank` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_sort` TEXT NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_digest` TINYINT(1) DEFAULT "1" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_password` VARCHAR(20) DEFAULT "" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `hide_forum_on_index` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `hide_forum_in_cat` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `display_moderators` TINYINT(1) DEFAULT "1" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `index_posts` TINYINT(1) DEFAULT "1" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_template` MEDIUMINT(8) UNSIGNED DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `stop_bumping` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_toggle` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `index_lasttitle` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `display_pic_alert` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_regdate_limit` MEDIUMINT(8) UNSIGNED DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `forum_subject_check` tinyint(1) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'forums ADD COLUMN `topic_password` TINYINT(1) DEFAULT "0" NOT NULL';

$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups MODIFY COLUMN `group_description` TEXT NOT NULL DEFAULT ""';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_allow_pm` TINYINT(2) DEFAULT "5" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_digest` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_amount` float DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_period` integer DEFAULT "1"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_period_basis` VARCHAR(10) DEFAULT "M"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_first_trial_fee` float DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_first_trial_period` integer DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_first_trial_period_basis` VARCHAR(10) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_second_trial_fee` float DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_second_trial_period` integer DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_second_trial_period_basis` VARCHAR(10) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_sub_recurring` integer DEFAULT "1"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_sub_recurring_stop` integer DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_sub_recurring_stop_num` integer DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_sub_reattempt` integer DEFAULT "1"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `allow_create_meeting` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_members_count` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_colored` TINYINT(1) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_colors` TEXT NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_order` INTEGER(255) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_rank_order` MEDIUMINT(8) default "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'groups ADD COLUMN `group_validate` TINYINT(1) default "1" NOT NULL';
	
$sql[] = 'ALTER TABLE ' . $table_prefix . 'posts ADD COLUMN `user_avatar` VARCHAR(100)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'posts ADD COLUMN `user_avatar_type` TINYINT NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'posts ADD COLUMN `rating_rank_id` SMALLINT UNSIGNED NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'posts ADD COLUMN `post_bluecard` TINYINT(1)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'posts ADD COLUMN `post_icon` TINYINT(2) UNSIGNED DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'posts ADD COLUMN `post_edit_user` MEDIUMINT(8) DEFAULT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'posts ADD COLUMN `post_attachment` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'posts ADD KEY `posts_ratingrankid` (rating_rank_id)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'posts ADD COLUMN `urgent_post` TINYINT(1) DEFAULT "0" NOT NULL';

$sql[] = 'ALTER TABLE ' . $table_prefix . 'posts_text MODIFY COLUMN `post_subject` VARCHAR(120) NOT NULL';

$sql[] = 'ALTER TABLE ' . $table_prefix . 'privmsgs ADD COLUMN `privmsgs_from_username` VARCHAR(25) DEFAULT "" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'privmsgs ADD COLUMN `privmsgs_to_username` VARCHAR(25) DEFAULT "" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'privmsgs ADD COLUMN `site_id` MEDIUMINT(8) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'privmsgs ADD COLUMN `room_id` MEDIUMINT(8) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'privmsgs ADD COLUMN `privmsgs_attachment` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'privmsgs ADD KEY `room_id` (room_id)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'privmsgs ADD KEY `site_id` (site_id)';

$sql[] = 'ALTER TABLE ' . $table_prefix . 'ranks ADD COLUMN `rank_group` MEDIUMINT(8) NOT NULL';

$sql[] = 'ALTER TABLE ' . $table_prefix . 'sessions ADD COLUMN `session_topic` INT(11) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'sessions ADD COLUMN `is_robot` VARCHAR(255) DEFAULT "0" NOT NULL';

$sql[] = 'ALTER TABLE ' . $table_prefix . 'smilies ADD COLUMN `smilies_order` SMALLINT(5) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'smilies ADD COLUMN `cat_id` SMALLINT(5) DEFAULT "0" NOT NULL';

$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes MODIFY COLUMN `themes_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes MODIFY COLUMN `th_class1` VARCHAR(100) DEFAULT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes MODIFY COLUMN `th_class2` VARCHAR(100) DEFAULT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes MODIFY COLUMN `th_class3` VARCHAR(100) DEFAULT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `theme_public` TINYINT(1) DEFAULT "1" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `adminfontcolor` VARCHAR(6) DEFAULT "FFA34F"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `adminbold` TINYINT(1) DEFAULT "1" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `supermodfontcolor` VARCHAR(6) DEFAULT "009900"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `supermodbold` TINYINT(1) DEFAULT "1" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `modfontcolor` VARCHAR(6) DEFAULT "006600"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `modbold` TINYINT(1) DEFAULT "1" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `playersfontcolor` VARCHAR(6) DEFAULT "0099CC"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `botfontcolor` VARCHAR(6) DEFAULT "9E8DA7"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `image_cfg` VARCHAR(100) DEFAULT "" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `theme_header` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `theme_footer` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `style_version` VARCHAR(6)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `hr_color1` VARCHAR(6) DEFAULT "E8F3FC"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `hr_color2` VARCHAR(6) DEFAULT "D5E8F9"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `hr_color3` VARCHAR(6) DEFAULT "B7D9F6"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `hr_color4` VARCHAR(6) DEFAULT "FCECE8"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `hr_color5` VARCHAR(6) DEFAULT "F9DDD5"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `hr_color6` VARCHAR(6) DEFAULT "FACCBF"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `hr_color7` VARCHAR(6) DEFAULT "E9FAEA"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `hr_color8` VARCHAR(6) DEFAULT "D5F9D6"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `hr_color9` VARCHAR(6) DEFAULT "B2EEB4"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `jb_color1` VARCHAR(6) DEFAULT "006EBB"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `jb_color2` VARCHAR(6) DEFAULT "FF6428"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `jb_color3` VARCHAR(6) DEFAULT "329600"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes ADD COLUMN `fontcolor4` VARCHAR(6)';
	
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes_name ADD COLUMN `hr_color1_name` CHAR(50)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes_name ADD COLUMN `hr_color2_name` CHAR(50)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes_name ADD COLUMN `hr_color3_name` CHAR(50)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes_name ADD COLUMN `hr_color4_name` CHAR(50)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes_name ADD COLUMN `hr_color5_name` CHAR(50)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes_name ADD COLUMN `hr_color6_name` CHAR(50)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes_name ADD COLUMN `hr_color7_name` CHAR(50)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes_name ADD COLUMN `hr_color8_name` CHAR(50)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes_name ADD COLUMN `hr_color9_name` CHAR(50)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes_name ADD COLUMN `jb_color1_name` CHAR(50)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes_name ADD COLUMN `jb_color2_name` CHAR(50)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes_name ADD COLUMN `jb_color3_name` CHAR(50)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'themes_name ADD COLUMN `fontcolor4_name` CHAR(50)';
	
$sql[] = 'ALTER TABLE ' . $table_prefix . 'topics ADD COLUMN `rating_rank_id` SMALLINT UNSIGNED NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'topics ADD COLUMN `topic_icon` tinyint(2) UNSIGNED DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'topics ADD COLUMN `topic_attachment` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'topics ADD COLUMN `title_compl_infos` VARCHAR(255)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'topics ADD COLUMN `title_compl_color` VARCHAR(6) DEFAULT "" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'topics ADD COLUMN `title_pos` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'topics ADD COLUMN `topic_priority` SMALLINT DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'topics ADD COLUMN `answer_status` TINYINT(1) UNSIGNED DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'topics ADD COLUMN `topic_password` VARCHAR(20) DEFAULT "" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'topics ADD KEY `topics_ratingrankid` (rating_rank_id)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'topics MODIFY COLUMN `topic_title` CHAR(120) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'topics TYPE=MYISAM';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'topics ADD FULLTEXT KEY topic_title (`topic_title`)';
	
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users MODIFY COLUMN `username` VARCHAR(99) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_allow_mass_pm` TINYINT(1) DEFAULT "2"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_allowswearywords` TINYINT(1) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_inactive_emls` TINYINT(1) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_inactive_last_eml` INT(11) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_popup_notes` TINYINT(1) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_clockformat` VARCHAR(12) DEFAULT "clock001.swf" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_allow_profile` TINYINT(1) DEFAULT "1" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_votewarnings` SMALLINT(5) DEFAULT "0" NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_profile_view` SMALLINT(5) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_last_profile_view` INT(11) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_profile_view_popup` TINYINT(1) DEFAULT "1"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_trophies` INT(10) NOT NULL DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_cheat_fix` INT(100) NOT NULL DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_game_playing` INT(10) NOT NULL DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_last_visit_page` VARCHAR(255) NOT NULL DEFAULT ""';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_games_today` INT(10) NOT NULL DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_last_playtype` VARCHAR(255) DEFAULT "parent" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_games_played` INT(10) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_game_pass` int(10) NOT NULL DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_games_pass_day` date NOT NULL DEFAULT "0000-00-00"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_time_playing` varchar(20) NOT NULL DEFAULT ""';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_settings` varchar(255) NOT NULL DEFAULT "info-1;;daily-1;;newest-1;;newest_count-3;;games-1;;games_count-40;;online-1"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_char_name` text NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_char_age` int(10) NOT NULL DEFAULT "1"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_char_from` varchar(255) NOT NULL DEFAULT ""';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_char_intrests` varchar(255) NOT NULL DEFAULT ""';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_char_img` varchar(255) NOT NULL DEFAULT ""';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_char_gender` smallint(1) NOT NULL DEFAULT "1"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_char_ge` int(10) NOT NULL DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_char_name_effects` text NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_char_title_effects` text NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_char_saying_effects` text NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_char_views` int(10) NOT NULL DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_char_title` varchar(255) NOT NULL DEFAULT ""';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `ina_char_saying` varchar(255) NOT NULL DEFAULT ""';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_view_log` INT DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_sound_pm` TINYINT(1) DEFAULT"0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `rating_status` TINYINT UNSIGNED NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_warnings` SMALLINT(5) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_items` TEXT';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_effects` CHAR(255)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_privs` CHAR(255)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_custitle` TEXT';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_specmsg` TEXT';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_trade` TEXT';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_notify_donation` TINYINT(1) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_points` BIGINT(20) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `admin_allow_points` TINYINT(1) DEFAULT "1" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_lastlogon` INT(11) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_totaltime` INT(11) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_totallogon` SMALLINT(5) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_totalpages` INT(11) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_birthday` MEDIUMINT(6) DEFAULT "999999" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_next_birthday_greeting` INT DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_from_flag` VARCHAR(25) NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_session_topic` INT(11) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_gender` tinyint DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_photo` VARCHAR(100)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_photo_type` TINYINT(4) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_showsigs` TINYINT(1) DEFAULT "1"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_showavatars` tinyint(1) DEFAULT "1"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `karma_plus` MEDIUMINT DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `karma_minus` MEDIUMINT DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `karma_time` bigint DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_realname` VARCHAR(50)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `irc_commands` VARCHAR (255) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_xfi` VARCHAR(255)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_post_color` VARCHAR(6)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_custom_post_color` VARCHAR(6)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `avatar_sticky` TINYINT NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_zipcode` VARCHAR(10)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_skype` VARCHAR(255)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD FULLTEXT (`user_skype`)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `kick_ban` INT(2) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_info` TEXT';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_gtalk` VARCHAR(255)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_stumble` VARCHAR(100)';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_digest_status` TINYINT(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_actviate_date` int(11) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_expire_date` int(11) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_jobs` INT(11) NOT NULL DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_notify_pm_text` tinyint(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_ftr` SMALLINT(1) NOT NULL DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_ftr_time` INT(11) NOT NULL DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `email_validation` tinyint(1) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_topic_moved_mail` TINYINT(1) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_topic_moved_pm` TINYINT(1) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_topic_moved_pm_notify` TINYINT(1) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `daily_post_count` MEDIUMINT(8) UNSIGNED DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `daily_post_limit` MEDIUMINT(8) UNSIGNED NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `daily_post_period` INT(11) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_wordwrap` SMALLINT(3) DEFAULT "80" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_allowsig` TINYINT(1) DEFAULT "1" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `group_priority` INTEGER(255) NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_lastpassword` VARCHAR(32) NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_lastpassword_time` INT(11) NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'users ADD COLUMN `user_transition` TINYINT(1) NOT NULL DEFAULT "1"';

$sql[] = 'ALTER TABLE ' . $table_prefix . 'user_group ADD COLUMN `digest_confirm_date` INT(11) DEFAULT "0" NOT NULL';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'user_group ADD COLUMN `ug_expire_date` INT(11) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'user_group ADD COLUMN `ug_active_date` INT(11) DEFAULT "0"';
$sql[] = 'ALTER TABLE ' . $table_prefix . 'user_group ADD COLUMN `group_moderator` TINYINT(1) NOT NULL';

$sql[] = 'ALTER TABLE ' . $table_prefix . 'vote_voters ADD COLUMN `vote_cast` TINYINT(4) UNSIGNED DEFAULT "0" NOT NULL';

// Change default phpBB/user values to sync with FullyModded setup
$sql[] = 'UPDATE ' . $table_prefix . 'config SET `config_value` = "uploads/user_avatars" WHERE `config_name` = "avatar_path"';
$sql[] = 'UPDATE ' . $table_prefix . 'config SET `config_value` = "images/avatars" WHERE `config_name` = "avatar_gallery_path"';
$sql[] = 'UPDATE ' . $table_prefix . 'config SET `config_value` = "1" WHERE `config_name` = "gzip_compress"';
$sql[] = 'UPDATE ' . $table_prefix . 'config SET `config_value` = "1" WHERE `config_name` = "default_style"';

$sql[] = 'UPDATE ' . $table_prefix . 'users SET `user_style` = "1"'; 
$sql[] = 'UPDATE ' . $table_prefix . 'users SET `admin_allow_points` = "1" WHERE `user_id` > 0';
$sql[] = 'UPDATE ' . $table_prefix . 'users SET `user_lastlogon` = `user_lastvisit`';
$sql[] = 'UPDATE ' . $table_prefix . 'users SET `user_session_time` = `user_lastlogon`';
$sql[] = 'UPDATE ' . $table_prefix . 'users SET `user_totallogon` = 1 WHERE `user_session_time` <> 0';
$sql[] = 'UPDATE ' . $table_prefix . 'users SET `user_level` = "3" WHERE `user_level` = "2"'; 

?>